# Generated by Django 4.2.11 on 2024-04-11 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='wingiftemail',
            name='number_selected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wingiftemail',
            name='prize_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wingiftemail',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.voucher'),
        ),
    ]
