# Generated by Django 4.2.11 on 2024-04-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_voucher_wingiftemail_number_selected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
