# Generated by Django 4.2.11 on 2024-04-11 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_voucher_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeProbability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=0, verbose_name='Money in USD')),
                ('percentage', models.FloatField(default=0.0, verbose_name='Percentage probability')),
            ],
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(max_length=6, null=True, unique=True, verbose_name='Voucher code of 6 characters'),
        ),
        migrations.AlterField(
            model_name='wingiftemail',
            name='number_selected',
            field=models.IntegerField(default=0, verbose_name='Box number selected'),
        ),
        migrations.AlterField(
            model_name='wingiftemail',
            name='prize_won',
            field=models.IntegerField(default=0, verbose_name='Prize money won'),
        ),
        migrations.AlterField(
            model_name='wingiftemail',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.voucher', verbose_name='A unique voucher number entered'),
        ),
    ]
